import { StoreModel } from './../../src/database/Store.model';

export const fixtures = () => {
  return samples.map(
    (store) =>
      new StoreModel({
        ...store,
        _id: store['uuid'],
        location: {
          type: 'Point',
          coordinates: [store['latitude'], store['longitude']],
        },
      }),
  );
};

const samples = [
  {
    city: 'Wommels',
    postalCode: '8731 AX',
    street: 'Terp',
    street2: '11',
    street3: '',
    addressName: 'Jumbo Wommels Terp',
    uuid: 'iGEKYx4XCWEAAAFIUL0YwKxK',
    longitude: '5.588159',
    latitude: '53.108561',
    complexNumber: '32126',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '6507',
    todayClose: '20:00',
  },
  {
    city: 'Woudenberg',
    postalCode: '3931 VH',
    street: "'t Schilt",
    street2: '18',
    street3: '',
    addressName: "Jumbo Woudenberg 't Schilt",
    uuid: 'TkcKYx4XoOkAAAFIVYgYwKxK',
    longitude: '5.412983',
    latitude: '52.081909',
    complexNumber: '31543',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '6346',
    todayClose: '20:00',
  },
  {
    city: 'Wouw',
    postalCode: '4724 EE',
    street: 'Kloosterstraat',
    street2: '8',
    street3: '',
    addressName: 'Jumbo Wouw Kloosterstraat',
    uuid: 'NsUKYx4XYc4AAAFM7eIcobsE',
    longitude: '4.388977',
    latitude: '51.520602',
    complexNumber: '33223',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '3608',
    todayClose: '20:00',
  },
  {
    city: 'Zaltbommel',
    postalCode: '5302 TA',
    street: 'Fiep Westendorpplein',
    street2: '12',
    street3: '',
    addressName: 'Jumbo Zaltbommel Fiep Westendorpplein',
    uuid: 'oBUKYx4X7QAAAAFINWQYwKMM',
    longitude: '5.251408',
    latitude: '51.802704',
    complexNumber: '32190',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3401',
    todayClose: '20:00',
  },
  {
    city: 'Zeeland',
    postalCode: '5411 EA',
    street: 'Kerkstraat',
    street2: '47',
    street3: '',
    addressName: 'Jumbo Zeeland Kerkstraat',
    uuid: 'iloKYx4XvKcAAAFIhf8YwKxJ',
    longitude: '5.674078',
    latitude: '51.696945',
    complexNumber: '32235',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '3513',
    todayClose: '20:00',
  },
  {
    city: 'Zeist',
    postalCode: '3705 HK',
    street: 'Johan van Oldenbarneveltlaan',
    street2: '96',
    street3: '',
    addressName: 'Jumbo Zeist Johan van Oldenbarneveltlaan',
    uuid: 'NpUKYx4XjHAAAAFMyzwcocAr',
    longitude: '5.239731',
    latitude: '52.098069',
    complexNumber: '33574',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3148',
    todayClose: '21:00',
  },
  {
    city: 'Zeist',
    postalCode: '3701 EX',
    street: 'Korte Steijnlaan',
    street2: '2',
    street3: '',
    addressName: 'Jumbo Zeist Korte Steijnlaan',
    uuid: 'rs0KYx4XxpwAAAFIkF0YwKrH',
    longitude: '5.248135',
    latitude: '52.088909',
    complexNumber: '32127',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '4921',
    todayClose: '21:00',
  },
  {
    city: 'Zeist',
    postalCode: '3706 AL',
    street: 'Laan van Vollenhove',
    street2: '2785-3001',
    street3: '',
    addressName: 'Jumbo Zeist Laan van Vollenhove',
    uuid: 'F3wKYx4X9CgAAAFIBUIYwKxK',
    longitude: '5.222160',
    latitude: '52.100900',
    complexNumber: '31436',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '4675',
    todayClose: '21:00',
  },
  {
    city: 'Zelhem',
    postalCode: '7021 XG',
    street: 'Bergstraat',
    street2: '1',
    street3: '',
    addressName: 'Jumbo Zelhem Bergstraat',
    uuid: 'bUsKYx4XxNMAAAFIZ7EYwKxK',
    longitude: '6.346952',
    latitude: '52.007206',
    complexNumber: '31533',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '6471',
    todayClose: '20:00',
  },
  {
    city: 'Zetten',
    postalCode: '6671 CA',
    street: 'Julianaplein',
    street2: '8',
    street3: '',
    addressName: 'Jumbo Zetten Teun van Blijderveen',
    uuid: 's6wKYx4X8vIAAAFIB.EYwKxJ',
    longitude: '5.711857',
    latitude: '51.929334',
    complexNumber: '33226',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3416',
    todayClose: '20:00',
  },
  {
    city: 'Zevenaar',
    postalCode: '6901 JC',
    street: 'Kampsingel',
    street2: '7',
    street3: '',
    addressName: 'Jumbo Zevenaar van Heemskerk Kampsingel',
    uuid: 'lOAKYx4XRzgAAAFJGxEYZ4CR',
    longitude: '6.078237',
    latitude: '51.931510',
    complexNumber: '33227',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3596',
    todayClose: '21:00',
  },
  {
    city: 'Zevenaar',
    postalCode: '6904 BD',
    street: 'van Oldebarneveldtlaan',
    street2: '34',
    street3: '',
    addressName: 'Jumbo Zevenaar van Heemskerk Oldebarneveldtlaan',
    uuid: 'uZwKYx4XyTMAAAFJ1w8YZ4CR',
    longitude: '6.064158',
    latitude: '51.930226',
    complexNumber: '32237',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3595',
    todayClose: '21:00',
  },
  {
    city: 'Zevenbergen',
    postalCode: '4761 TW',
    street: 'Zandberg',
    street2: '4',
    street3: '',
    addressName: 'Jumbo Zevenbergen Zandberg',
    uuid: 'NeYKYx4XpocAAAFIOoQYwKxK',
    longitude: '4.590481',
    latitude: '51.647711',
    complexNumber: '31587',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '6332',
    todayClose: '20:00',
  },
  {
    city: 'Zevenhuizen',
    postalCode: '2761 AL',
    street: 'Dorpsstraat',
    street2: '129',
    street3: '',
    addressName: 'Jumbo Zevenhuizen Dorpsstraat',
    uuid: 'p1AKYx4XTtsAAAFJ7xAYZ4CR',
    longitude: '4.579452',
    latitude: '52.012988',
    complexNumber: '33575',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3722',
    todayClose: '20:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2718 GH',
    street: 'Groenblauwlaan',
    street2: '109',
    street3: '',
    addressName: 'Jumbo Zoetermeer Groenblauwlaan',
    uuid: 'Zd8KYx4XPhwAAAFIaNsYwKxJ',
    longitude: '4.494595',
    latitude: '52.039918',
    complexNumber: '33267',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3405',
    todayClose: '21:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2717 HS',
    street: 'Kentgensplein',
    street2: '3',
    street3: '',
    addressName: 'Jumbo Zoetermeer Kentgensplein',
    uuid: 'qhoKYx4XrEkAAAFIxlEYwKWg',
    longitude: '4.478458',
    latitude: '52.066911',
    complexNumber: '30504',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '6391',
    todayClose: '20:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2716 CW',
    street: 'Middelwaard',
    street2: '52',
    street3: '',
    addressName: 'Jumbo Zoetermeer Middelwaard',
    uuid: 'M1wKYx4XuR0AAAFI0MgYwKxJ',
    longitude: '4.468679',
    latitude: '52.055543',
    complexNumber: '33231',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3091',
    todayClose: '22:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2721 NJ',
    street: 'Oosterheemplein',
    street2: '548',
    street3: '',
    addressName: 'Jumbo Zoetermeer Oosterheemplein',
    uuid: 'DoAKYx4XYSMAAAFIB30YwKxK',
    longitude: '4.541213',
    latitude: '52.059349',
    complexNumber: '32174',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '4934',
    todayClose: '21:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2719 CH',
    street: 'Quirinegang',
    street2: '201',
    street3: '',
    addressName: 'Jumbo Zoetermeer Quirinegang',
    uuid: 'vNYKYx4XH7YAAAFZar8nMJqK',
    longitude: '4.477336',
    latitude: '52.043506',
    complexNumber: '32224',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '3177',
    todayClose: '20:00',
  },
  {
    city: 'Zoetermeer',
    postalCode: '2727 AK',
    street: 'Meeuwenveld',
    street2: '8',
    street3: '',
    addressName: 'Jumbo Zoetermeer Ruijter Leidsewallen',
    uuid: 'uMMKYx4XoXoAAAFNLZhasEYQ',
    longitude: '4.510174',
    latitude: '52.069415',
    complexNumber: '33230',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3669',
    todayClose: '21:00',
  },
  {
    city: 'Zoeterwoude',
    postalCode: '2381 EN',
    street: 'Dorpsstraat',
    street2: '34',
    street3: '',
    addressName: 'Jumbo Zoeterwoude Jan Versluis',
    uuid: 'mfoKYx4X7kYAAAFIKCYYwKxK',
    longitude: '4.496790',
    latitude: '52.121030',
    complexNumber: '33579',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '3708',
    todayClose: '20:00',
  },
  {
    city: 'Zuidlaren',
    postalCode: '9471 GR',
    street: 'Stationsweg',
    street2: '8',
    street3: '',
    addressName: 'Jumbo Zuidlaren Stationsweg',
    uuid: '7oQKYx4X5fEAAAFIIT4YwKxK',
    longitude: '6.685443',
    latitude: '53.093135',
    complexNumber: '30090',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'Supermarkt',
    sapStoreID: '4663',
    todayClose: '21:00',
  },
  {
    city: 'Zuidwolde',
    postalCode: '7921 HR',
    street: 'Wethouder Klunderstraat',
    street2: '16',
    street3: '',
    addressName: 'Jumbo Zuidwolde Termeulen',
    uuid: 'hyoKYx4XnsAAAAFIsicYwKxK',
    longitude: '6.428343',
    latitude: '52.675426',
    complexNumber: '33584',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '3711',
    todayClose: '21:00',
  },
  {
    city: 'Zutphen',
    postalCode: '7207 PV',
    street: 'Rudolf Steinerlaan',
    street2: '47',
    street3: '',
    addressName: 'Jumbo Zutphen Rudolf Steinerlaan',
    uuid: 'te0KYx4XWzAAAAFIJIoYwKxK',
    longitude: '6.244301',
    latitude: '52.126134',
    complexNumber: '31573',
    showWarningMessage: true,
    todayOpen: '08:00',
    locationType: 'SupermarktPuP',
    collectionPoint: true,
    sapStoreID: '6350',
    todayClose: '20:00',
  },
];
